---
version: "3.7"
services:
  security:
    image: jenkinsci/jenkins
    container_name: jenkins
    dns_search: exemplo.com.br
    restart: always
    network_mode: "host"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    volumes:
      - /opt/jenkins:/var/jenkins_home
      - /etc/hosts:/etc/hosts
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.8.8
    ports:
      - "8080/tcp:8080/tcp"
      - "50000/tcp:50000/tcp"
      - "50022/tcp:50022/tcp"
#    expose:
#      - "8080/tcp"
    extra_hosts:
      - "jenkins.exemplo.com.br:172.16.238.10"  

...
## a simple human would
## docker run -d --name jenkins -v /opt/jenkins:/var/jenkins_home -p 8080:8080 -p 50000:50000 jenkinsci/jenkins
